// <auto-generated />
using System;
using Gruppuppgift_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gruppuppgift_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Gruppuppgift_backend.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int?>("DealershipId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Gruppuppgift_backend.Entities.CarDealership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("DealershipName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CarDealership");
                });

            modelBuilder.Entity("Gruppuppgift_backend.Entities.Car", b =>
                {
                    b.HasOne("Gruppuppgift_backend.Entities.CarDealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId");

                    b.Navigation("Dealership");
                });
#pragma warning restore 612, 618
        }
    }
}
